### PR TITLE
Should fix #52 and #53

### LINKED ISSUE #52: .users() will return only one user if connected before bot joined
When users are already connected to the server and the bot joins after them .users() will only return one user and not all of them.

### PR DESCRIPTION
**Pull request by Prior99**
Renamed properties read from protobuf. There might be more issues like this, I did not audit the whole code.

### CODE REVIEW

**Comment by justinmchase** [comment]
:+1:

**Comment by Prior99** [comment]
@Rantanen I would really love to see this merged and published to npm as the library in it's current state is not useable to me. Thank you :)

**Comment by Rantanen** [comment]
Yeah, sorry. I've been busy with work and didn't have time to look at the build failure.

Now that you took care of it, I've got no problem to merge this in. :)

**Comment by Rantanen** [comment]
Pushed to NPM as version 0.3.2

**Comment by Prior99** [comment]
Thank you :)

**Pull request merged**
