### PR TITLE
Broadcast message to channel and sub-channels

### PR DESCRIPTION
**Pull request by daveoon**
Add a broadcast flag to send text message to sub-channels as well.

### CODE REVIEW

**Comment by Rantanen** [comment]
What are you doing, Codacy?! D:

I'll need to look at that at some point. At least the curly bits are definitely not intended.

On the other hand, any chance you could split the if/elses on different lines?

```js
if( broadcast )
    this.client.sendMessage(...);
else
    this.client.sendMessage(...);
```

... just something I'm too used to. ._.

**Comment by daveoon** [comment]
> What are you doing, Codacy?! D:
> 
> I'll need to look at that at some point. At least the curly bits are definitely not intended.
> 
> On the other hand, any chance you could split the if/elses on different lines?
> 
> ```js
> if( broadcast )
>     this.client.sendMessage(...);
> else
>     this.client.sendMessage(...);
> ```
> 
> ... just something I'm too used to. ._.

Do you need to me change to suit your standard? I can do this and resend the pull request

**Comment by Rantanen** [comment]
Oh, yeah. Sorry. That was aimed at you.

On the other hand, it seems there's a pile of eslint issues around anyway, so once I get home from the office today I'll probably just merge this in and do some style changes anyway. So if you find time to do that change in the next few hours, go for it - but it's okay if you don't!

**Comment by Rantanen** [comment]
Merged! Thanks for this!

Also noted that the new parameter was missing documentation, but took care of that together with the style changes.

The change should be out in Version 0.3.19

**Pull request merged**
