### PR TITLE
Fix ready event

### PR DESCRIPTION
**Pull request by Prior99**
Emit ready only when really everything is initialized.

### CODE REVIEW

**Comment by Rantanen** [comment]
Hm. Looking at the existing Mumble codebase, the `PermissionQuery` is not part of the handshake. The server sends: `ServerSync`, `ServerConfig` and `SuggestConfig` during the authentication and then considers the connection to be OK. At this point I believe the client can start sending audio, fiddling with users, etc.

When the user joins a channel (automatically) the `PermissionQuery` gets sent. Given every user joins a channel I think it makes sense to assume that all users get `PermissionQuery` during connection - at least I didn't see a way to skip it by looking at the server code. So it kind of does make sense to wait for that until the `ready` event.

However I'm curious for the reasons to do so? What is it needed for?

From what I saw in the code, the server sends only the permissions for the current channel and the immediate parent automatically. So when we receive the 'ready' state, there's still a lot of channels that do not have the permissions set.

Would it be better to tweak the API in such a way that the `Channel` would have an asynchronous `getPermissions` method? Then we wouldn't need to care whether the permissions are already received or whether they need to be fetched from the server.

```javascript
Channel.prototype.getPermissions = function( callback ) {

  // If the permissions are cached, invoke callback with those cached permissions.
  if( this.permissions ) {
    return process.nextTick( callback.bind( null, this.permission ) );
  }

  // Otherwise query the server for permissions and wait for the response.
  this.wrapper.sendMessage( 'QueryPermissions', { channel: this.id });
  this.wrapper.once( 'queryPermissions-' + this.id, function( permissions ) {
    this.permissions = permissions;
    callback( permissions );
  }.bind( this ) );
}
```

**Comment by Prior99** [comment]
@Rantanen agreed. Fixed. Permissions may follow in a later pr.

**Comment by Rantanen** [comment]
Had a stab at it myself. Any idea how to decode them though?

    Root permissions: 134743822

**Comment by Rantanen** [comment]
Nevermind! Found it.

https://github.com/mumble-voip/mumble/blob/840a31de0e217f7908d3872b7cd76568ad28ccb1/src/ACL.h#L46

**Comment by Prior99** [comment]
I would like to keep permission in another pullrequest.

**Comment by Rantanen** [comment]
Oh, yeah. Of course. I just forgot to merge this. Wasn't waiting for permissions :)

**Comment by Rantanen** [comment]
Are you working on the permissions method at the moment or should I finish what I started?

**Comment by Prior99** [comment]
No I dont. Sorry. Also I will have no time next week so you will have to stay on this alone for the next 5 days.

**Pull request merged**
