### PR TITLE
Add User.kick/ban

### PR DESCRIPTION
**Pull request by tjhorner**
Allows bots to kick users, useful for moderating chat.

### CODE REVIEW

**Comment by tjhorner** [comment]
Hooray for Travis builds... I'll fix that.

**Comment by Prior99** [comment]
:+1:

**Comment by Prior99** [comment]
Instead of having a parameter ```ban``` how about adding a second method for banning people?

**Comment by tjhorner** [comment]
Sure. This time, the build failing isn't my fault. If you want, I have a 24/7 Mumble server at `mumble.horner.tj` that you can test on.

**Comment by tjhorner** [comment]
Oh wait, forgot to actually make `reason` optional... heh

**Comment by Rantanen** [comment]
Looks good! No idea what's wrong with the travis tests so ignoring those for now.

**Comment by Rantanen** [comment]
> The most important restriction for pull requests is about secure environment variables

Figures. Need to come up with a dedicated test instance of Mumble. It was set to use one used with pile of people so didn't want to publish the address.

**Comment by tjhorner** [comment]
Well as I said earlier, you could always use mine. 4 or 5 people are usually on it per day, I just set it up for a couple of friends.

**Pull request merged**
