### PR TITLE
Add method to register another user

### PR DESCRIPTION
**Pull request by Prior99**
Will close #109.

### CODE REVIEW

**Comment by Prior99** [comment]
@Rantanen I am somewhat confused by the codacy bot. I saw singlequotes basically all over the project. Should I address all of these issues? I believe the Travis is failing since a long time. Also, the `user_id` of course needs to be snake_case as it's a mumble internal field.

**Comment by Prior99** [comment]
@Rantanen, hey, do you need anything else to be done on this branch? Otherwise I'd really appreciate a merge and a release :)

**Comment by Rantanen** [comment]
I needed a reminder. :)

**Comment by Rantanen** [comment]
The merge is now published as version 0.3.14. Thanks for the PR!

**Pull request merged**
